### ISSUE TITLE
Error: "Plugin is missing setup function"

### ISSUE THREAD

**Issue by jonit-dev** [wangzongming/vite-plugin-require#11]
Hi there,

I'm trying to use the plugin as following:
```
import { esbuildCommonjs, viteCommonjs } from '@originjs/vite-plugin-commonjs';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';
import EnvironmentPlugin from 'vite-plugin-environment';
import vitePluginRequire from 'vite-plugin-require';
import requireTransform from 'vite-plugin-require-transform';
import tsconfigPaths from 'vite-tsconfig-paths';


// https://vitejs.dev/config/
export default defineConfig({
  
  plugins: [
    tsconfigPaths(),
    react({
      babel: {
        plugins: [
          [
            'babel-plugin-styled-components',
            {
              displayName: true,
              fileName: false,
            },
          ],
        ],
      },
    }),
    EnvironmentPlugin('all'),
    viteCommonjs(),
    requireTransform({
      fileRegex: /\.ts\.tsx$/,
    }),
    vitePluginRequire({
      fileRegex: /\.ts\.tsx$/,
      log: (a) => console.log(a)
    }),
  ],
  server: process.env.IS_DOCKER
    ? {
        host: '0.0.0.0',
      }
    : null,
  optimizeDeps: {
    esbuildOptions: {
      plugins: [
        // Solves:
        // https://github.com/vitejs/vite/issues/5308
        esbuildCommonjs(['react-flagpack']),
        vitePluginRequire({
          // @fileRegex RegExp
          // optional：default file processing rules are as follows
          // fileRegex:/(.jsx?|.tsx?|.vue)$/
        }),
      ],
    },
  },
});
//# sourceMappingURL=vite.config.js.map


```

Then I get a:

```✘ [ERROR] [plugin vite-plugin-require] Plugin is missing a setup function

    /home/jonit/personal-projects/rpg-engine/rpg-client/node_modules/esbuild/lib/main.js:794:16:
      794 │           throw new Error(`Plugin is missing a setup function`);
          ╵                 ^

    at handlePlugins (/home/jonit/personal-projects/rpg-engine/rpg-client/node_modules/esbuild/lib/main.js:794:17)
    at Object.buildOrServe (/home/jonit/personal-projects/rpg-engine/rpg-client/node_modules/esbuild/lib/main.js:1145:7)
    at /home/jonit/personal-projects/rpg-engine/rpg-client/node_modules/esbuild/lib/main.js:2087:17
    at new Promise (<anonymous>)
    at Object.build (/home/jonit/personal-projects/rpg-engine/rpg-client/node_modules/esbuild/lib/main.js:2086:14)
    at Object.build (/home/jonit/personal-projects/rpg-engine/rpg-client/node_modules/esbuild/lib/main.js:1935:51)
    at /home/jonit/personal-projects/rpg-engine/rpg-client/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:38997:54
    at Array.map (<anonymous>)
    at scanImports (/home/jonit/personal-projects/rpg-engine/rpg-client/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:38997:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Build failed with 1 error:
/home/jonit/personal-projects/rpg-engine/rpg-client/node_modules/esbuild/lib/main.js:794:16: ERROR: [plugin: vite-plugin-require] Plugin is missing a setup function
```

**Comment by wangzongming** [comment]
This configuration is not needed, or you can change it to this
fileRegex: /\.(ts|tsx)$/, 
I'm sorry I didn't reproduce your question here.

You can try to comment out other plugins or page files to find out what is causing the problem🧐.

**Comment by wangzongming** [comment]
Hi. One more question.
`optimizeDeps.esbuildOptions.plugins`
 No need to configure `vitePluginRequire()`

**Comment by wangzongming** [comment]
> 

Problems should be here, ` optimizeDeps.esbuildOptions.plugins[vitePluginRequire()]`, comments can be solved
