### ISSUE TITLE
Cannot read properties of undefined (reading 'moduleGraph')

### ISSUE THREAD

**Issue by jasonHzq** [wangzongming/vite-plugin-require#12]
TypeError: Cannot read properties of undefined (reading 'moduleGraph')
    at Object.<anonymous> (node_modules/_vite-plugin-css-modules@0.0.1@vite-plugin-css-modules/dist/index.js:165:50)
    at step (node_modules/_vite-plugin-css-modules@0.0.1@vite-plugin-css-modules/dist/index.js:44:23)
    at Object.next (node_modules/_vite-plugin-css-modules@0.0.1@vite-plugin-css-modules/dist/index.js:25:53)
    at fulfilled (node_modules/_vite-plugin-css-modules@0.0.1@vite-plugin-css-modules/dist/index.js:16:58)

**Comment by wangzongming** [comment]
The complete replay code needs to be given. And the problem is not `vite-plugin-require`
